# Welcome to Jekyll!
#

# Site settings
title: Steve Leathers | Portland, Oregon Realtor | steveleathers.com
description: |
  I'm a Realtor at [Inhabit](http://www.inhabitportland.com), and I live in Portland, Oregon.
owner: Steve Leathers # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: steve@inhabitportland.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://steveleathers.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/steveleathers
  instagram: https://instagram.com/steveleathers
  linkedin-square: https://linkedin.com/in/steveleathers
  facebook-official: https://facebook.com/SteveLeathersRealtor
  google-plus-square: https://plus.google.com/u/0/+steveleathers
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
